# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-19 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HearthstoneCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardId', models.CharField(db_index=True, max_length=32, unique=True)),
                ('dbfId', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('cardSet', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=64)),
                ('playerClass', models.CharField(max_length=64)),
                ('locale', models.CharField(max_length=16)),
            ],
        ),
    ]
